from .alumnos import ListadoAlumnosView, ImportarAlumnosView, EditarAlumnoView, CargaFormsetAlumnosView
from .asistencias import DetalleAsistenciasAlumnoView, ListaAsistenciasView
from .comunicados import CrearComunicadoView, TablonComunicadosView
from .calificaciones import DetalleCalificacionesAlumnoView, ListaCalificacionesView
from .cargos import ListaCargosView
from .profesores import ProfesorListView