# Generated by Django 6.0.4 on 2026-05-08 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(blank=True, max_length=30)),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True, help_text='Define si el alumno es parte de la institución actualmente.')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='AsignacionCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha en la que inicia en este cargo específico', verbose_name='Fecha de Toma de Posesión')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si el cargo sigue activo', null=True, verbose_name='Fecha de Cese')),
                ('resolucion', models.CharField(blank=True, help_text='Nro de Resolución o Disposición', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cargo está vigente actualmente')),
            ],
            options={
                'verbose_name': 'Asignación de Cargo',
                'verbose_name_plural': 'Asignaciones de Cargos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionPreceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Absente'), ('J', 'Justificada')], default='P', max_length=1)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('AULA', 'Aula'), ('LAB.', 'Laboratorio'), ('S.U.M', 'S.U.M'), ('BIBLIO.', 'Biblioteca')], default='AULA', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Burbuja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Burbuja',
                'verbose_name_plural': 'Burbujas',
            },
        ),
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciclo Lectivo',
                'verbose_name_plural': 'Ciclos Lectivos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(help_text='Ingrese el año (ej: 1 al 7)', validators=[django.core.validators.MinValueValidator(1, message='El nivel mínimo es 1.'), django.core.validators.MaxValueValidator(7, message='El nivel máximo permitido es 7.')])),
                ('division', models.PositiveIntegerField(help_text='Ingrese el número de división', validators=[django.core.validators.MinValueValidator(1, message='La división mínima es 1.'), django.core.validators.MaxValueValidator(15, message='La división máxima permitida es 15.')])),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nivel', 'division'],
            },
        ),
        migrations.CreateModel(
            name='Dictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dictado de Materia',
                'verbose_name_plural': 'Dictados de Materias',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_taller', models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B')], max_length=1, null=True, verbose_name='Grupo de Taller')),
                ('estado_final', models.CharField(choices=[('CURSANDO', 'Cursando'), ('PASE', 'Pase'), ('EGRESADO', 'Egresado'), ('ABANDONO', 'Abandono/Pase')], default='CURSANDO', max_length=20)),
            ],
            options={
                'verbose_name': 'Historial Académico',
                'verbose_name_plural': 'Historiales Académicos',
                'ordering': ['-ciclo_lectivo__anio', 'alumno__persona__apellido'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horario de Clase',
                'verbose_name_plural': 'Horarios de Clases',
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Intensificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la instancia de intensificación')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Nota numérica única del intento', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Nota de Intensificación',
                'verbose_name_plural': 'Notas de Intensificación',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('AULA', 'Aula/Teoría'), ('TALLER', 'Taller/Práctica')], default='AULA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NotaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.IntegerField(choices=[(1, '1º Cuatrimestre'), (2, '2º Cuatrimestre')])),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Nota de Actividad',
                'verbose_name_plural': 'Notas de Actividades',
            },
        ),
        migrations.CreateModel(
            name='NotaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('1C', 'Primer Cuatrimestre'), ('2C', 'Segundo Cuatrimestre'), ('DIC', 'Diciembre'), ('FEB', 'Febrero'), ('FINAL', 'Nota Final Anual')], max_length=10)),
                ('valor_numerico', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('valor_conceptual', models.CharField(blank=True, choices=[('TEA', 'Trayectoria Educativa Avanzada (TEA)'), ('TEP', 'Trayectoria Educativa en Proceso (TEP)'), ('TED', 'Trayectoria Educativa Discontinua (TED)')], max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Nota de Etapa',
                'verbose_name_plural': 'Notas de Etapa',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(help_text='Número de documento sin puntos', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener entre 7 y 8 dígitos numéricos, sin puntos ni espacios.', regex='^\\d{7,8}$')])),
                ('cuil', models.CharField(help_text='CUIL sin guiones', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El CUIL debe tener el formato XX-XXXXXXXX-X.', regex='^\\d{2}-\\d{8}-\\d{1}$')])),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('numero_legajo', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('domicilio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonalCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Personal con Cargo',
                'verbose_name_plural': 'Personal con Cargos',
            },
        ),
        migrations.CreateModel(
            name='PersonalNoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre el personal (ej. turno de limpieza, tareas específicas)')),
            ],
            options={
                'verbose_name': 'Personal No Docente',
                'verbose_name_plural': 'Personal No Docente',
            },
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Preceptor',
                'verbose_name_plural': 'Preceptores',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cargo',
                'verbose_name_plural': 'Tipos de Cargos',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('valor_falta', models.DecimalField(decimal_places=2, default=0.5, help_text='Ejemplo: 0.5 para media falta, 1.0 para falta completa.', max_digits=3, validators=[django.core.validators.MinValueValidator(0, message='El valor no puede ser negativo.'), django.core.validators.MaxValueValidator(1, message='El valor de una falta no puede ser mayor a 1.0.')])),
            ],
        ),
    ]
