# Generated by Django 6.0.4 on 2026-05-08 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_academica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='burbuja_sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_academica.burbuja', verbose_name='Burbuja que asistió'),
        ),
        migrations.AddConstraint(
            model_name='ciclolectivo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='unique_active_ciclo_lectivo'),
        ),
        migrations.AddField(
            model_name='burbuja',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burbujas', to='gestion_academica.ciclolectivo'),
        ),
        migrations.AddField(
            model_name='asignacionpreceptor',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.ciclolectivo'),
        ),
        migrations.AddField(
            model_name='asignacionpreceptor',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.curso'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictados', to='gestion_academica.ciclolectivo'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictados', to='gestion_academica.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.especialidad'),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='gestion_academica.alumno'),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='burbuja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones', to='gestion_academica.burbuja', verbose_name='Burbuja (Opcional)'),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='gestion_academica.ciclolectivo'),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_inscriptos', to='gestion_academica.curso'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion_academica.historialacademico'),
        ),
        migrations.AddField(
            model_name='horariodictado',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_academica.aula'),
        ),
        migrations.AddField(
            model_name='horariodictado',
            name='dictado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestion_academica.dictado'),
        ),
        migrations.AddField(
            model_name='intensificacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intensificaciones', to='gestion_academica.alumno'),
        ),
        migrations.AddField(
            model_name='intensificacion',
            name='dictado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intensificaciones', to='gestion_academica.dictado'),
        ),
        migrations.AddField(
            model_name='materia',
            name='especialidad',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío si la materia es común a todas las especialidades (Troncal).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_academica.especialidad'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictados', to='gestion_academica.materia'),
        ),
        migrations.AddField(
            model_name='notaactividad',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_actividades', to='gestion_academica.alumno'),
        ),
        migrations.AddField(
            model_name='notaactividad',
            name='dictado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_actividades', to='gestion_academica.dictado'),
        ),
        migrations.AddField(
            model_name='notaetapa',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_etapas', to='gestion_academica.alumno'),
        ),
        migrations.AddField(
            model_name='notaetapa',
            name='dictado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_etapas', to='gestion_academica.dictado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario de sistema vinculado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to='gestion_academica.persona'),
        ),
        migrations.AddField(
            model_name='personalcargo',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cargo', to='gestion_academica.persona'),
        ),
        migrations.AddField(
            model_name='asignacioncargo',
            name='persona_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion_academica.personalcargo'),
        ),
        migrations.AddField(
            model_name='personalnodocente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_nodocente', to='gestion_academica.persona'),
        ),
        migrations.AddField(
            model_name='preceptor',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_preceptor', to='gestion_academica.persona'),
        ),
        migrations.AddField(
            model_name='asignacionpreceptor',
            name='preceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion_academica.preceptor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesor', to='gestion_academica.persona'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dictados', to='gestion_academica.profesor'),
        ),
        migrations.AddField(
            model_name='personalcargo',
            name='cargos',
            field=models.ManyToManyField(related_name='personal_asignado', through='gestion_academica.AsignacionCargo', to='gestion_academica.tipocargo'),
        ),
        migrations.AddField(
            model_name='asignacioncargo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_historicas', to='gestion_academica.tipocargo'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.turno'),
        ),
        migrations.AddConstraint(
            model_name='burbuja',
            constraint=models.UniqueConstraint(fields=('nombre', 'ciclo_lectivo'), name='unique_nombre_burbuja_por_ciclo'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nivel', 'division', 'especialidad')},
        ),
        migrations.AlterUniqueTogether(
            name='historialacademico',
            unique_together={('alumno', 'ciclo_lectivo')},
        ),
        migrations.AddConstraint(
            model_name='horariodictado',
            constraint=models.CheckConstraint(condition=models.Q(('horario_inicio__lt', models.F('horario_fin'))), name='check_horario_inicio_menor_fin'),
        ),
        migrations.AlterUniqueTogether(
            name='notaetapa',
            unique_together={('dictado', 'alumno', 'etapa')},
        ),
        migrations.AlterUniqueTogether(
            name='asignacionpreceptor',
            unique_together={('preceptor', 'curso', 'ciclo_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='dictado',
            unique_together={('materia', 'curso', 'ciclo_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('inscripcion', 'fecha', 'turno')},
        ),
    ]
