# Generated by Django 6.0.4 on 2026-05-21 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='notaactividad',
            name='cuatrimestre',
            field=models.IntegerField(choices=[(1, '1º Cuatrimestre'), (2, '2º Cuatrimestre')], db_index=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(help_text='CUIL sin guiones', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El CUIL debe tener 11 dígitos numéricos sin guiones.', regex='^\\d{11}$')]),
        ),
    ]
