# Generated by Django 6.0.4 on 2026-05-21 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0003_alter_asistencia_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['inscripcion', 'fecha'], name='idx_asistencia_insc_fecha'),
        ),
        migrations.AddIndex(
            model_name='notaactividad',
            index=models.Index(fields=['dictado', 'alumno'], name='idx_notaact_dictado_alumno'),
        ),
    ]
