# Generated by Django 6.0.4 on 2026-05-26 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0004_asistencia_idx_asistencia_insc_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificada')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='InscripcionDictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('REGULAR', 'Regular'), ('RECURSANTE', 'Recursante'), ('PREVIA', 'Previa')], default='REGULAR', max_length=15)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_dictados', to='gestion_academica.alumno')),
                ('ciclo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.ciclolectivo')),
                ('dictado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_inscriptos', to='gestion_academica.dictado')),
            ],
            options={
                'verbose_name': 'Inscripción a Dictado',
                'verbose_name_plural': 'Inscripciones a Dictados',
                'unique_together': {('alumno', 'dictado', 'ciclo_lectivo')},
            },
        ),
    ]
