# Generated by Django 6.0.4 on 2026-05-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0005_alter_asistencia_estado_inscripciondictado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictado',
            name='cupof',
            field=models.IntegerField(blank=True, null=True, verbose_name='CUPOF'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='forma_ingreso',
            field=models.CharField(blank=True, choices=[('MAD', 'MAD'), ('REUBICADO', 'Reubicado'), ('ACTO_PUBLICO', 'Acto Público'), ('ACTO_PUBLICO_DIGITAL', 'Acto Público Digital'), ('DESTINO_DEFINITIVO', 'Destino Definitivo'), ('PROPUESTA_NOMBRAMIENTO', 'Propuesta Nombramiento'), ('PROYECTO_ELECCION', 'Proyecto y Elección'), ('DISPOSICION', 'Disposición'), ('OTROS', 'Otros')], max_length=30, null=True, verbose_name='Forma de Ingreso'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PID'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='secuencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Secuencia'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='situacion_revista',
            field=models.CharField(blank=True, choices=[('TITULAR', 'Titular'), ('INTERINO', 'Interino'), ('SUPLENTE', 'Suplente'), ('PROVICIONAL', 'Provicional')], max_length=20, null=True, verbose_name='Situación de Revista'),
        ),
        migrations.AddField(
            model_name='dictado',
            name='toma_posesion',
            field=models.DateField(blank=True, null=True, verbose_name='Toma de Posesión'),
        ),
    ]
