# Generated by Django 6.0.4 on 2026-05-31 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0006_dictado_cupof_dictado_forma_ingreso_dictado_pid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido del Comunicado')),
                ('visibilidad', models.CharField(choices=[('GLOBAL', 'Global (Solo Logueados)'), ('ESTUDIANTES', 'Solo Estudiantes'), ('DOCENTES', 'Solo Docentes')], default='GLOBAL', max_length=15, verbose_name='Visibilidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
