# Generated by Django 6.0.4 on 2026-05-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0006_dictado_cupof_dictado_forma_ingreso_dictado_pid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dictado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dictado',
            name='grupo',
            field=models.CharField(choices=[('UNICO', 'Curso Completo / Único'), ('A', 'Grupo A'), ('B', 'Grupo B')], default='UNICO', max_length=10, verbose_name='Grupo de Dictado'),
        ),
        migrations.AlterField(
            model_name='dictado',
            name='situacion_revista',
            field=models.CharField(blank=True, choices=[('TITULAR', 'Titular'), ('INTERINO', 'Interino'), ('SUPLENTE', 'Suplente'), ('PROVISIONAL', 'Provisional')], max_length=20, null=True, verbose_name='Situación de Revista'),
        ),
        migrations.AlterUniqueTogether(
            name='dictado',
            unique_together={('materia', 'curso', 'ciclo_lectivo', 'grupo')},
        ),
    ]
