# Generated by Django 6.0.4 on 2026-05-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0007_alter_dictado_unique_together_dictado_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='datos_pase',
            field=models.TextField(blank=True, help_text='Descripción o motivos de la baja (ej. escuela de destino, razones personales, etc.).', null=True),
        ),
    ]
