# Generated by Django 6.0.4 on 2026-06-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0008_alumno_datos_pase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictado',
            name='grupo',
            field=models.CharField(choices=[('UNICO', 'Curso Completo / Único'), ('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C')], default='UNICO', max_length=10, verbose_name='Grupo de Dictado'),
        ),
    ]
