# Generated by Django 6.0.4 on 2026-06-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0009_alter_dictado_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='tipo',
            field=models.CharField(choices=[('AULA', 'Aula'), ('LAB.', 'Laboratorio'), ('S.U.M', 'S.U.M'), ('BIBLIO.', 'Biblioteca'), ('TALLER.', 'Taller')], default='AULA', max_length=10),
        ),
    ]
