# Generated by Django 6.0.4 on 2026-06-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0011_asignacioncargo_cupof_asignacioncargo_forma_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacioncargo',
            name='toma_posesion',
        ),
    ]
