# Generated by Django 6.0.4 on 2026-06-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0012_remove_asignacioncargo_toma_posesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcargo',
            name='cargos',
        ),
    ]
