# Generated by Django 6.0.4 on 2026-06-26 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0013_remove_personalcargo_cargos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaetapa',
            name='valor_numerico',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
