# Generated by Django 5.2.1 on 2026-06-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0014_alter_notaetapa_valor_numerico'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaetapa',
            name='valoracion_previa',
            field=models.CharField(blank=True, choices=[('TEA', 'Trayectoria Educativa Avanzada (TEA)'), ('TEP', 'Trayectoria Educativa en Proceso (TEP)'), ('TED', 'Trayectoria Educativa Discontinua (TED)')], max_length=3, null=True, verbose_name='Valoración previa'),
        ),
    ]
